[package]
name = "ascii_converter"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.4"
imageproc = "0.25.0"
rusttype = "0.9.2"
clap = { version = "4.1.4", features = ["derive"] }
ansi_term = "0.12.1"
ab_glyph = "0.2.29"
